## LS

In [9]:
from wildetect.core.visualization.labelstudio_manager import LabelStudioManager
from wildata.converters.labelstudio.labelstudio_schemas import Result, Task
from pathlib import Path

In [13]:
ls_manager = LabelStudioManager(
    url="http://127.0.0.1:8080",
    api_key='4f3c25bad9334596c5b2c3b270a2d3105c8b5d4a',
    download_resources=False,
)

In [14]:
task = Task.from_sdk_task(ls_manager.get_task(31346))

[18:04:52] INFO     HTTP Request: GET http://127.0.0.1:8080/api/tasks/31346/ "HTTP/1.1 200 OK"      ]8;id=509682;file://d:\PhD\workspace\wildetect\.venv\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=631244;file://d:\PhD\workspace\wildetect\.venv\Lib\site-packages\httpx\_client.py#1025\1025]8;;\

In [7]:
task

Task(id=31346, data=TaskData(image='/data/local-files/?d=PhD%5CData%20per%20camp%5CWet%20season%5CKapiri%5CCamp%204_5%5CRep%201%20-%20tiled%5CDJI_20240205120057_0074_1.JPG'), annotations=[Annotation(id=5347, completed_by=1, result=[Result(id='dRlyzncAq0', type='rectanglelabels', from_name='label', to_name='image', original_width=1802, original_height=3056, image_rotation=0, value=ResultValue(x=40.83157792340108, y=36.940130263723006, width=5.179017603595831, height=1.965010478234416, rotation=0.0, rectanglelabels=['buffalo']), origin=<ResultOrigin.PREDICTION_CHANGED: 'prediction-changed'>, score=0.823920488357544), Result(id='9gVLB4w3_b', type='rectanglelabels', from_name='label', to_name='image', original_width=1802, original_height=3056, image_rotation=0, value=ResultValue(x=43.92091452612332, y=36.49416618946335, width=5.3517492973844165, height=1.436806723709506, rotation=0.0, rectanglelabels=['buffalo']), origin=<ResultOrigin.PREDICTION_CHANGED: 'prediction-changed'>, score=0.8092572689056396), Result(id='HTuk2YIfrP', type='rectanglelabels', from_name='label', to_name='image', original_width=1802, original_height=3056, image_rotation=0, value=ResultValue(x=62.087734954867855, y=41.53417142898, width=4.509912082278372, height=2.4361163533794943, rotation=0.0, rectanglelabels=['buffalo']), origin=<ResultOrigin.PREDICTION_CHANGED: 'prediction-changed'>, score=0.7550106048583984), Result(id='QDSbu2VUzB', type='rectanglelabels', from_name='label', to_name='image', original_width=1802, original_height=3056, image_rotation=0, value=ResultValue(x=40.58591109089196, y=42.29291077140081, width=4.3381615180288335, height=1.5348233747685711, rotation=0.0, rectanglelabels=['buffalo']), origin=<ResultOrigin.MANUAL: 'manual'>, score=None)], was_cancelled=False, ground_truth=False, created_at=datetime.datetime(2024, 5, 9, 9, 47, 50, 148886, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2024, 5, 9, 9, 47, 50, 148886, tzinfo=TzInfo(UTC)), draft_created_at=datetime.datetime(2024, 5, 9, 9, 47, 19, 903344, tzinfo=TzInfo(UTC)), lead_time=57.762, prediction=None, result_count=0, unique_id=None, import_id=None, last_action=None, bulk_created=False, task=31346, project=12, updated_by=1, parent_prediction=8052, parent_annotation=None, last_created_by=None)], drafts=[], predictions=[8052], meta={}, created_at=datetime.datetime(2024, 5, 7, 23, 27, 21, 330813, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2024, 5, 9, 9, 47, 50, 174147, tzinfo=TzInfo(UTC)), inner_id=148, total_annotations=1, cancelled_annotations=0, total_predictions=1, comment_count=0, unresolved_comment_count=0, last_comment_updated_at=None, project=12, updated_by=None, comment_authors=[])

In [11]:
task.image_path

'D:\\\\PhD\\Data per camp\\Wet season\\Kapiri\\Camp 4_5\\Rep 1 - tiled\\DJI_20240205120057_0074_1.JPG'

In [12]:
Path(task.image_path).exists()

True

In [6]:
task.data

TaskData(image='/data/local-files/?d=PhD%5CData%20per%20camp%5CWet%20season%5CKapiri%5CCamp%204_5%5CRep%201%20-%20tiled%5CDJI_20240205120057_0074_1.JPG')

## Load duplicates

In [7]:
import pandas as pd
import numpy as np

In [14]:
df_duplicated = pd.read_csv("../animal-duplicates.csv").rename(columns={"image": "task_id","bounding box":"bbox_id"})
df_duplicated.head(3)

  season  camp  Project ID  task_id     bbox_id  species  duplicate
0    Wet  K4_5          12    31346  dRlyzncAq0  buffalo          2
1    Wet  K4_5          12    31348  g1997mnNM0  buffalo          2
2    Wet  K4_5          12    31788  xOn9_xr2XK     roan          3

In [12]:
df_duplicated['bbox_id'].nunique()

245

In [13]:
df_loaded = pd.read_csv("../animal-duplicates_annotations.csv")
df_loaded.head(3)

,task_id,x_pixel,y_pixel,width_pixel,height_pixel,label,score,origin,bbox_id
0,39409,657.764755,34.688291,45.727425,34.074927,sable,0.492378,prediction,hbUXekrzK3
1,31346,735.785034,1128.890381,93.325897,60.050720,buffalo,0.823920,prediction,dRlyzncAq0
2,31788,1605.102190,553.608555,80.144758,52.590664,roan,0.586624,prediction,xOn9_xr2XK

In [11]:
df_loaded['bbox_id'].nunique()

98

In [15]:
df_loaded_pred = pd.read_csv("../animal-duplicates_predictions.csv")
df_loaded_pred.head(3)

,task_id,x_pixel,y_pixel,width_pixel,height_pixel,label,score,origin,bbox_id
0,39409,657.764755,34.688291,45.727425,34.074927,sable,0.492378,prediction,hbUXekrzK3
1,39411,671.625054,1101.370863,54.369485,26.958404,sable,0.347088,prediction,X22tB0VjlM
2,31346,735.785034,1128.890381,93.325897,60.050720,buffalo,0.823920,prediction,dRlyzncAq0

In [16]:
df_loaded_pred['bbox_id'].nunique()

240

In [17]:
intersection = np.intersect1d(df_loaded['bbox_id'], df_duplicated['bbox_id'])
intersection.shape

(98,)

In [18]:
intersection = np.intersect1d(df_loaded_pred['bbox_id'], df_duplicated['bbox_id'])
intersection.shape

(240,)