## LS

In [8]:
from wildetect.core.visualization.labelstudio_manager import LabelStudioManager
from wildata.converters.labelstudio.labelstudio_schemas import Result, Task
from pathlib import Path
from wildetect.core.data import DroneImage
from wildetect.core.config_models import FlightSpecs

In [2]:
ls_manager = LabelStudioManager(
    url="http://127.0.0.1:8080",
    api_key='4f3c25bad9334596c5b2c3b270a2d3105c8b5d4a',
    download_resources=False,
)

In [3]:
task = ls_manager.get_task(190628,as_sdk_task=False)

In [4]:
task

Task(id=190628, data=TaskData(image='/data/local-files?d=PhD\\Data per camp\\Dry season\\Kapiri\\Farm\\DJI_202310040946_014_Kapiri-Farm3\\DJI_20231004131109_0087.JPG'), annotations=[Annotation(id=69752, completed_by=1, result=[Result(id='688c565aebd3949892d2763d', type=<ResultType.RECTANGLELABELS: 'rectanglelabels'>, from_name='detections', to_name='image', original_width=8192, original_height=5460, image_rotation=0, value=ResultValue(x=34.619887932205295, y=0.1282051282051283, width=0.963608161544699, height=0.8651838062289492, rotation=0.0, rectanglelabels=['sable']), origin=<ResultOrigin.PREDICTION_CHANGED: 'prediction-changed'>, score=None), Result(id='688c565aebd3949892d2763e', type=<ResultType.RECTANGLELABELS: 'rectanglelabels'>, from_name='detections', to_name='image', original_width=8192, original_height=5460, image_rotation=0, value=ResultValue(x=37.7197265625, y=44.761904761904766, width=0.87890625, height=0.9523809523809524, rotation=0.0, rectanglelabels=['sable']), origin=<ResultOrigin.PREDICTION_CHANGED: 'prediction-changed'>, score=None), Result(id='688c565aebd3949892d2763f', type=<ResultType.RECTANGLELABELS: 'rectanglelabels'>, from_name='detections', to_name='image', original_width=8192, original_height=5460, image_rotation=0, value=ResultValue(x=39.3310546875, y=41.35531135531135, width=1.1962890625, height=1.391941391941392, rotation=0.0, rectanglelabels=['sable']), origin=<ResultOrigin.PREDICTION_CHANGED: 'prediction-changed'>, score=None), Result(id='688c565aebd3949892d27640', type=<ResultType.RECTANGLELABELS: 'rectanglelabels'>, from_name='detections', to_name='image', original_width=8192, original_height=5460, image_rotation=0, value=ResultValue(x=37.5, y=42.234432234432234, width=0.5615234375, height=1.3553113553113554, rotation=0.0, rectanglelabels=['sable']), origin=<ResultOrigin.PREDICTION_CHANGED: 'prediction-changed'>, score=None), Result(id='ZFVHZCaE_G', type=<ResultType.RECTANGLELABELS: 'rectanglelabels'>, from_name='detections', to_name='image', original_width=8192, original_height=5460, image_rotation=0, value=ResultValue(x=37.145455602707436, y=44.19652742243998, width=0.6103047785064817, height=1.2590609936074912, rotation=0.0, rectanglelabels=['sable']), origin=<ResultOrigin.MANUAL: 'manual'>, score=None), Result(id='U15K6GyfKv', type=<ResultType.RECTANGLELABELS: 'rectanglelabels'>, from_name='detections', to_name='image', original_width=8192, original_height=5460, image_rotation=0, value=ResultValue(x=18.632713130667238, y=46.18146873722299, width=0.29282596632602775, height=0.4393462117477611, rotation=0.0, rectanglelabels=['sable']), origin=<ResultOrigin.MANUAL: 'manual'>, score=None), Result(id='GwsCxSHIL3', type=<ResultType.RECTANGLELABELS: 'rectanglelabels'>, from_name='detections', to_name='image', original_width=8192, original_height=5460, image_rotation=0, value=ResultValue(x=20.59636961073588, y=45.26401047151442, width=0.46507653475310207, height=0.646097370217305, rotation=0.0, rectanglelabels=['sable']), origin=<ResultOrigin.MANUAL: 'manual'>, score=None), Result(id='90dlb-bphK', type=<ResultType.RECTANGLELABELS: 'rectanglelabels'>, from_name='detections', to_name='image', original_width=8192, original_height=5460, image_rotation=0, value=ResultValue(x=28.562958400488046, y=31.256619485203295, width=0.41340136422497764, height=1.1500533189867994, rotation=0.0, rectanglelabels=['sable']), origin=<ResultOrigin.MANUAL: 'manual'>, score=None), Result(id='c6HIan3liK', type=<ResultType.RECTANGLELABELS: 'rectanglelabels'>, from_name='detections', to_name='image', original_width=8192, original_height=5460, image_rotation=0, value=ResultValue(x=18.262374408549032, y=43.41774327860276, width=0.22392573895519519, height=0.736551002047726, rotation=0.0, rectanglelabels=['warthog']), origin=<ResultOrigin.MANUAL: 'manual'>, score=None), Result(id='5cmSbrGDKO', type=<ResultType.RECTANGLELABELS: 'rectanglelabels'>, from_name='detections', to_name='image', original_width=8192, original_height=5460, image_rotation=0, value=ResultValue(x=17.81452293063864, y=42.849177592811536, width=0.3531136652755045, height=0.6073315280042593, rotation=0.0, rectanglelabels=['warthog']), origin=<ResultOrigin.MANUAL: 'manual'>, score=None)], was_cancelled=False, ground_truth=False, created_at=datetime.datetime(2025, 8, 1, 9, 56, 0, 157948, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2025, 8, 1, 9, 56, 0, 157948, tzinfo=TzInfo(UTC)), draft_created_at=datetime.datetime(2025, 8, 1, 9, 53, 45, 290501, tzinfo=TzInfo(UTC)), lead_time=166.284, prediction=None, result_count=0, unique_id=None, import_id=None, last_action=None, bulk_created=False, task=190628, project=129, updated_by=1, parent_prediction=239177, parent_annotation=None, last_created_by=None)], drafts=[], predictions=[239177], meta={}, created_at=datetime.datetime(2025, 8, 1, 5, 53, 42, 402823, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2025, 8, 1, 9, 56, 0, 183949, tzinfo=TzInfo(UTC)), inner_id=4, total_annotations=1, cancelled_annotations=0, total_predictions=1, comment_count=0, unresolved_comment_count=0, last_comment_updated_at=None, project=129, updated_by=None, comment_authors=[])

In [5]:
task.image_path

'D:\\\\PhD\\Data per camp\\Dry season\\Kapiri\\Farm\\DJI_202310040946_014_Kapiri-Farm3\\DJI_20231004131109_0087.JPG'

In [6]:
Path(task.image_path).exists()

True

In [10]:
    flight_specs = FlightSpecs(sensor_height=24, focal_length=35, flight_height=180)

drone_image = DroneImage.from_ls_task(task=task,flight_specs=flight_specs)

In [12]:
drone_image.get_non_empty_annotations()

[Detection(bbox=[2836, 7, 2914, 54], confidence=1.0, class_id=0, class_name='sable', metadata=None, id='688c565aebd3949892d2763d', geographic_footprint=GeographicBounds(north=251008.55133229747, south=250823.33021229747, east=7349264.071694738, west=7349140.621094738, lat_center=-23.94951536111111, lon_center=30.552519166666666, width_px=8192, height_px=5460, gsd=2.261), gps_loc='23 56m 56.2565s S, 30 33m 8.13059s E, 0.831353km', image_gps_loc='23 56m 58.2553s S, 30 33m 9.069s E, 0.8313529999999999km', parent_image='D:\\\\PhD\\Data per camp\\Dry season\\Kapiri\\Farm\\DJI_202310040946_014_Kapiri-Farm3\\DJI_20231004131109_0087.JPG'),
 Detection(bbox=[3090, 2444, 3162, 2496], confidence=1.0, class_id=0, class_name='sable', metadata=None, id='688c565aebd3949892d2763e', geographic_footprint=GeographicBounds(north=251008.55133229747, south=250823.33021229747, east=7349264.071694738, west=7349140.621094738, lat_center=-23.94951536111111, lon_center=30.552519166666666, width_px=8192, height_px=5460, gsd=2.261), gps_loc='23 56m 58.052s S, 30 33m 8.29736s E, 0.831353km', image_gps_loc='23 56m 58.2553s S, 30 33m 9.069s E, 0.8313529999999999km', parent_image='D:\\\\PhD\\Data per camp\\Dry season\\Kapiri\\Farm\\DJI_202310040946_014_Kapiri-Farm3\\DJI_20231004131109_0087.JPG'),
 Detection(bbox=[3222, 2257, 3320, 2333], confidence=1.0, class_id=0, class_name='sable', metadata=None, id='688c565aebd3949892d2763f', geographic_footprint=GeographicBounds(north=251008.55133229747, south=250823.33021229747, east=7349264.071694738, west=7349140.621094738, lat_center=-23.94951536111111, lon_center=30.552519166666666, width_px=8192, height_px=5460, gsd=2.261), gps_loc='23 56m 57.9253s S, 30 33m 8.41567s E, 0.831353km', image_gps_loc='23 56m 58.2553s S, 30 33m 9.069s E, 0.8313529999999999km', parent_image='D:\\\\PhD\\Data per camp\\Dry season\\Kapiri\\Farm\\DJI_202310040946_014_Kapiri-Farm3\\DJI_20231004131109_0087.JPG'),
 Detection(bbox=[3072, 2306, 3118, 2380], confidence=1.0, class_id=0, class_name='sable', metadata=None, id='688c565aebd3949892d27640', geographic_footprint=GeographicBounds(north=251008.55133229747, south=250823.33021229747, east=7349264.071694738, west=7349140.621094738, lat_center=-23.94951536111111, lon_center=30.552519166666666, width_px=8192, height_px=5460, gsd=2.261), gps_loc='23 56m 57.9583s S, 30 33m 8.27434s E, 0.831353km', image_gps_loc='23 56m 58.2553s S, 30 33m 9.069s E, 0.8313529999999999km', parent_image='D:\\\\PhD\\Data per camp\\Dry season\\Kapiri\\Farm\\DJI_202310040946_014_Kapiri-Farm3\\DJI_20231004131109_0087.JPG'),
 Detection(bbox=[3042, 2413, 3092, 2481], confidence=1.0, class_id=0, class_name='sable', metadata=None, id='ZFVHZCaE_G', geographic_footprint=GeographicBounds(north=251008.55133229747, south=250823.33021229747, east=7349264.071694738, west=7349140.621094738, lat_center=-23.94951536111111, lon_center=30.552519166666666, width_px=8192, height_px=5460, gsd=2.261), gps_loc='23 56m 58.0343s S, 30 33m 8.25052s E, 0.831353km', image_gps_loc='23 56m 58.2553s S, 30 33m 9.069s E, 0.8313529999999999km', parent_image='D:\\\\PhD\\Data per camp\\Dry season\\Kapiri\\Farm\\DJI_202310040946_014_Kapiri-Farm3\\DJI_20231004131109_0087.JPG'),
 Detection(bbox=[1526, 2521, 1550, 2545], confidence=1.0, class_id=0, class_name='sable', metadata=None, id='U15K6GyfKv', geographic_footprint=GeographicBounds(north=251008.55133229747, south=250823.33021229747, east=7349264.071694738, west=7349140.621094738, lat_center=-23.94951536111111, lon_center=30.552519166666666, width_px=8192, height_px=5460, gsd=2.261), gps_loc='23 56m 58.078s S, 30 33m 7.02732s E, 0.831353km', image_gps_loc='23 56m 58.2553s S, 30 33m 9.069s E, 0.8313529999999999km', parent_image='D:\\\\PhD\\Data per camp\\Dry season\\Kapiri\\Farm\\DJI_202310040946_014_Kapiri-Farm3\\DJI_20231004131109_0087.JPG'),
 Detection(bbox=[1687, 2471, 1725, 2506], confidence=1.0, class_id=0, class_name='sable', metadata=None, id='GwsCxSHIL3', geographic_footprint=GeographicBounds(north=251008.55133229747, south=250823.33021229747, east=7349264.071694738, west=7349140.621094738, lat_center=-23.94951536111111, lon_center=30.552519166666666, width_px=8192, height_px=5460, gsd=2.261), gps_loc='23 56m 58.0471s S, 30 33m 7.16221s E, 0.831353km', image_gps_loc='23 56m 58.2553s S, 30 33m 9.069s E, 0.8313529999999999km', parent_image='D:\\\\PhD\\Data per camp\\Dry season\\Kapiri\\Farm\\DJI_202310040946_014_Kapiri-Farm3\\DJI_20231004131109_0087.JPG'),
 Detection(bbox=[2339, 1706, 2373, 1769], confidence=1.0, class_id=0, class_name='sable', metadata=None, id='90dlb-bphK', geographic_footprint=GeographicBounds(north=251008.55133229747, south=250823.33021229747, east=7349264.071694738, west=7349140.621094738, lat_center=-23.94951536111111, lon_center=30.552519166666666, width_px=8192, height_px=5460, gsd=2.261), gps_loc='23 56m 57.5037s S, 30 33m 7.69212s E, 0.831353km', image_gps_loc='23 56m 58.2553s S, 30 33m 9.069s E, 0.8313529999999999km', parent_image='D:\\\\PhD\\Data per camp\\Dry season\\Kapiri\\Farm\\DJI_202310040946_014_Kapiri-Farm3\\DJI_20231004131109_0087.JPG'),
 Detection(bbox=[1496, 2370, 1514, 2410], confidence=1.0, class_id=0, class_name='warthog', metadata=None, id='c6HIan3liK', geographic_footprint=GeographicBounds(north=251008.55133229747, south=250823.33021229747, east=7349264.071694738, west=7349140.621094738, lat_center=-23.94951536111111, lon_center=30.552519166666666, width_px=8192, height_px=5460, gsd=2.261), gps_loc='23 56m 57.9725s S, 30 33m 7.00293s E, 0.831353km', image_gps_loc='23 56m 58.2553s S, 30 33m 9.069s E, 0.8313529999999999km', parent_image='D:\\\\PhD\\Data per camp\\Dry season\\Kapiri\\Farm\\DJI_202310040946_014_Kapiri-Farm3\\DJI_20231004131109_0087.JPG'),
 Detection(bbox=[1459, 2339, 1488, 2372], confidence=1.0, class_id=0, class_name='warthog', metadata=None, id='5cmSbrGDKO', geographic_footprint=GeographicBounds(north=251008.55133229747, south=250823.33021229747, east=7349264.071694738, west=7349140.621094738, lat_center=-23.94951536111111, lon_center=30.552519166666666, width_px=8192, height_px=5460, gsd=2.261), gps_loc='23 56m 57.9464s S, 30 33m 6.97784s E, 0.831353km', image_gps_loc='23 56m 58.2553s S, 30 33m 9.069s E, 0.8313529999999999km', parent_image='D:\\\\PhD\\Data per camp\\Dry season\\Kapiri\\Farm\\DJI_202310040946_014_Kapiri-Farm3\\DJI_20231004131109_0087.JPG')]

In [13]:
drone_image.get_non_empty_predictions()

[]

## Load duplicates

In [7]:
import pandas as pd
import numpy as np

In [14]:
df_duplicated = pd.read_csv("../animal-duplicates.csv").rename(columns={"image": "task_id","bounding box":"bbox_id"})
df_duplicated.head(3)

  season  camp  Project ID  task_id     bbox_id  species  duplicate
0    Wet  K4_5          12    31346  dRlyzncAq0  buffalo          2
1    Wet  K4_5          12    31348  g1997mnNM0  buffalo          2
2    Wet  K4_5          12    31788  xOn9_xr2XK     roan          3

In [12]:
df_duplicated['bbox_id'].nunique()

245

In [13]:
df_loaded = pd.read_csv("../animal-duplicates_annotations.csv")
df_loaded.head(3)

,task_id,x_pixel,y_pixel,width_pixel,height_pixel,label,score,origin,bbox_id
0,39409,657.764755,34.688291,45.727425,34.074927,sable,0.492378,prediction,hbUXekrzK3
1,31346,735.785034,1128.890381,93.325897,60.050720,buffalo,0.823920,prediction,dRlyzncAq0
2,31788,1605.102190,553.608555,80.144758,52.590664,roan,0.586624,prediction,xOn9_xr2XK

In [11]:
df_loaded['bbox_id'].nunique()

98

In [15]:
df_loaded_pred = pd.read_csv("../animal-duplicates_predictions.csv")
df_loaded_pred.head(3)

,task_id,x_pixel,y_pixel,width_pixel,height_pixel,label,score,origin,bbox_id
0,39409,657.764755,34.688291,45.727425,34.074927,sable,0.492378,prediction,hbUXekrzK3
1,39411,671.625054,1101.370863,54.369485,26.958404,sable,0.347088,prediction,X22tB0VjlM
2,31346,735.785034,1128.890381,93.325897,60.050720,buffalo,0.823920,prediction,dRlyzncAq0

In [16]:
df_loaded_pred['bbox_id'].nunique()

240

In [17]:
intersection = np.intersect1d(df_loaded['bbox_id'], df_duplicated['bbox_id'])
intersection.shape

(98,)

In [18]:
intersection = np.intersect1d(df_loaded_pred['bbox_id'], df_duplicated['bbox_id'])
intersection.shape

(240,)